### ISSUE TITLE
怎么启动forge版

### ISSUE THREAD

**Issue by XiaoYejunAWA** [baibao132/SquareMinecraftLauncherCore#3]
我只能启动原版，启动不了forge版

**Comment by baibao132** [comment]
请提供一下错误信息 可以通过stratgame类事件获取到

**Comment by baibao132** [comment]
请提供一下错误信息 可以从startgame类获取到

**Comment by baibao132** [comment]
请提供一下错误信息 可以从startgame类事件获取到

**Comment by XiaoYejunAWA** [comment]
debug:
[16:07:01] [main/DEBUG] [FML]:     D:\code\program\HXC\bin\Debug\.minecraft\versions\1.12.2\1.12.2-natives
[16:07:01] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\code\program\HXC\bin\Debug\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ArtifactVersion
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.findLibraryFolder(LibraryManager.java:126) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:77) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.artifact.versioning.ArtifactVersion
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.findLibraryFolder(LibraryManager.java:126) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:77) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 5 more
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
lastest:
[16:07:01] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\code\program\HXC\bin\Debug\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ArtifactVersion
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.findLibraryFolder(LibraryManager.java:126) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:77) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.artifact.versioning.ArtifactVersion
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.findLibraryFolder(LibraryManager.java:126) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:77) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 5 more
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:07:01] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by baibao132** [comment]
新版本已发布，如果还出现问题可以看看调整Java路径为jre或jdk再看看
